types:
  Product:
    properties:
      name: { nullable: false }
      description: { nullable: false }
      image: { range: "Text" }

  Offer:
    properties:
      url: { nullable: false }
      price: { nullable: false, range: "Number" }
      priceCurrency: { nullable: false }


# php vendor/bin/schema generate-types src/ config/schema.yaml
#
