easy_admin:
  site_name: 'Best tropicals out there!'
  user:
    name_property_path: 'email'
  entities:
    Product:
      class: App\Entity\Product
      list:
        title: "Products list"
        fields:
          - { property: 'name' }
          - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
          - {property: 'offers' }
        actions: ['show']
      show:
        fields:
          - {property: 'image', type: 'image', base_path: '%app.path.product_images%'}

      form:
        fields:
          - { property: 'name' }
          - { property: 'description' }
          - { property: 'imageFile', type: 'vich_image' }
          - { property: 'offers', type_options: {by_reference: false}}


    Offer:
      class: App\Entity\Offer
      list:
        title: "Offers list"
        fields: ['url','price','priceCurrency', 'product']
        actions: ['show']

  design:
    menu:
      - Product
      - Offer
      - { label: 'Logout', url: '/logout' }
